services:
  backend:
    build: .
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "82", "--reload" ]
    ports:
      - "8002:82"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1


  nginx:
    image: nginx:latest
    ports:
      - "82:82"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: